'''El modelo de scanvi está pensado para refinar el espacio latente generado por scvi. 
El objeto adata se espera que esté integrado por scvi y que haya sido anotado con el pipeline de General Anno

El pipeline completo scvi-scanvi se puede ver en 

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scrna/harmonization.html


Se espera que previamente se hayan ejecutado: 

1. SCPreprocessing (genera adata)
2. Before Integration (genera adata_normalized)

3. IntegrationScvi (genera adata_scvi)
4. GeneralAnnoBeforeScAnvi (genera adata_GenAnno)

This script IntegrationScAnvi is the 5th step of the pipeline. It refines the latent space generated by scvi using scanvi.


'''
import scanpy as sc
import scvi
import os
import torch

print(f"Using torch version {torch.__version__}")
print(f"Using scvi version {scvi.__version__}")
print(f"CUDA: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

if torch.cuda.is_available():
    accelerator = "gpu"
else:
    accelerator = "cpu"

torch.manual_seed(311224)

#################### Environment Variables ############################
DATA_DIR = os.getenv("DATA_DIR")
MODEL_DIR = os.getenv("MODEL_DIR")
CELLTYPE = os.getenv("CELL_TYPE") # cell type used as reference 
SCANVI_LATENT_KEY = "X_scANVI"

#################### Load Adata ############################
adata = sc.read_h5ad(os.path.join(DATA_DIR,"GenAnnoPostScvi.h5ad"))
adata.obs[CELLTYPE] = adata.obs[CELLTYPE].astype('category')
print(f"Unique cell types: {adata.obs[CELLTYPE].cat.categories}")

# Select only HVGs
adata_hvg = adata[:, adata.var.highly_variable].copy()

##################### Load the model architecture ############################
scvi_ref_path = os.path.join(MODEL_DIR, "scvi_model_cuda")
model = scvi.model.SCVI.load(scvi_ref_path,adata_hvg)

# Create scanvi model from the scvi model
scanvi_model = scvi.model.SCANVI.from_scvi_model(model, 
                                      unlabeled_category="unknown",
                                      labels_key=CELLTYPE) 
# Train the model
scanvi_model.train(max_epochs=40, n_samples_per_label=100)

# Save scanvi model 
scanvi_ref_path = os.path.join(MODEL_DIR, "scanvi_model_cuda_refinement")
scanvi_model.save(scanvi_ref_path, overwrite=True)
print(f"Model saved in {scanvi_ref_path}")

##################### Transfer latent space to adata #############
adata.obsm[SCANVI_LATENT_KEY] = scanvi_model.get_latent_representation()
sc.pp.neighbors(adata, use_rep=SCANVI_LATENT_KEY)
sc.tl.leiden(adata)
sc.tl.umap(adata)
adata.write_h5ad(os.path.join(DATA_DIR,"adata_scanvi_cuda_refinement.h5ad"))
